### ISSUE TITLE
Allow bulk download of episodes in ZIP

### ISSUE THREAD

**Issue by Invictaz** [PodcastGenerator/PodcastGenerator#161]
Select multiple episodes and download them at once in a zip file

**Comment by emilengler** [comment]
You can already select multiple episodes with FTP and download them over that protocol. Is it really necessary to do it on the web interface site?

**Comment by Invictaz** [comment]
I won't give end users access to my FTP so that's why I asked.

**Comment by emilengler** [comment]
Ok, will work on that

**Comment by emilengler** [comment]
Ok looks like it is not that easy to allow episode download by ZIP. This is because it can take lots of time and lots of resources and lots of disk space until a ZIP archive was created. Most clients will already give up because of a timeout. Also many webservers probably block such a action because of a too high resource usage. I'm currently working on an alternative way to bulk download episodes.

It will work like this. Get a curl command which you paste into your terminal or cmd.exe. The program curl which does the task is pre installed on Windows 10, macOS and most Linux distributions. I will also add a guide to it.

**Comment by emilengler** [comment]
Thanks, added
