### ISSUE TITLE
List episodes to be published in the future

### ISSUE THREAD

**Issue by z3a** [PodcastGenerator/PodcastGenerator#175]
I just upgraded to PG3.0 and try to upload a new episode to be published in a couple of days. I need to edit it, but since the post isn't published yet I can't view it in the episodes list, so it's impossible to edit or delete it. There is a workaround to solve this issue?

**Comment by emilengler** [comment]
There is a workaround. Go to your `media/` folder and edit the `.xml` file associated with your filename. But I think it's a good idea to list future episodes when you are signed in as an admin will work on that soon

**Comment by cmpilato** [comment]
One relatively simple way to do this:  add a boolean parameter to `getEpisodes()` that means "don't filter out future episodes".  When returned episodes from that function, decorate future ones with a flag.  When in admin mode, you pass the flag as TRUE and decorate (in the theme template) the future episodes as such; otherwise pass FALSE for the flag and you don't see them in the listing at all.

**Comment by wilhen01** [comment]
I just experienced this issue, would be great to have a fix

**Comment by coldacid** [comment]
This has been developed and will be in the 3.2 release.
