### ISSUE TITLE
Req: Apple Situational Podcast tags

### ISSUE THREAD

**Issue by messagedj** [PodcastGenerator/PodcastGenerator#185]
Could you please add the Apple Podcast Apple recommended RSS tags that are released by apple in April 2019? They increase your online viability. 

- <itunes:title> | An episode title specific for Apple Podcasts.
- <itunes:episode> | An episode number.
- <itunes:season> | The episode season number.
- <itunes:episodeType> | The episode type. (If an episode is a trailer or bonus content)
- <itunes:block> | The episode show or hide status.

See [https://help.apple.com/itc/podcasts_connect/#/itcb54353390](https://help.apple.com/itc/podcasts_connect/#/itcb54353390)

**Comment by emilengler** [comment]
ok

**Comment by ryangurn** [comment]
I am going to start working towards implementing this. Mainly going to be working on adding options to the upload area to help handle these options. They will be optional as that is the way that they are in the apple documentation as well.

**Comment by emilengler** [comment]
I can fully understand you!
However the problem is: What will happen to previous episodes? The biggest problem in PG is the backwards compatibility. Guess why we still don't use SQL databases. So how for example would we go with the season/episode system for previous episodes? Put all of them into season 1?

**Comment by ryangurn** [comment]
@emilengler to tell you the truth, I dont know why we are not using SQL, because even at minimum SQLite support would make all of our lives easier so that we do not need to endlessly parse XML. Doing all of the XML processing each time the page is requested causes decreases in performance. 

I do not have any specific inclination to change it to SQL because I understand that backward compatibility is important but I might add that supporting SQL as an alternative does not have many downsides other than adding to the complexity of the code. This can easily be managed however with a simple ORM.

**Comment by emilengler** [comment]
> I do not have any specific inclination to change it to SQL because I understand that backward compatibility is important but I might add that supporting SQL as an alternative does not have many downsides other than adding to the complexity of the code. This can easily be managed however with a simple ORM.

This is indeed a good idea! I would be open for such a PR. Also we could make the upgrader to convert the old entries automatically to an SQLite database

**Comment by ryangurn** [comment]
The upgrader would be one of the first things that I would start with after agreeing upon some sort of db schema. @emilengler it might be a good idea for us to connect and decide on a unified db schema so that we can ensure consistency as we add that functionality. I would say that this should be something slated for 3.2 or 3.2+ so that we can ensure its properly compatible with future ideas.

**Comment by messagedj** [comment]
Thnx for the efforts guys! Can't wait to see this coming alive.

**Comment by emilengler** [comment]
> The upgrader would be one of the first things that I would start with after agreeing upon some sort of db schema. @emilengler it might be a good idea for us to connect and decide on a unified db schema so that we can ensure consistency as we add that functionality. I would say that this should be something slated for 3.2 or 3.2+ so that we can ensure its properly compatible with future ideas. 

Sure thing! Feel free to contact me over my E-Mail (can be found everywhere).

**Comment by coldacid** [comment]
Progress as of 3.2:

- [ ] itunes:title | An episode title specific for Apple Podcasts.
- [x] itunes:episode | An episode number.
- [x] itunes:season | The episode season number.
- [ ] itunes:episodeType | The episode type. (If an episode is a trailer or bonus content)
- [ ] itunes:block | The episode show or hide status.

**Comment by coldacid** [comment]
itunes:episodeType should be coming in 3.3. I just implemented it on the train this morning.

**Comment by messagedj** [comment]
Awesome!

**Comment by messagedj** [comment]
> itunes:episodeType should be coming in 3.3. I just implemented it on the train this morning.

AWESOME!!

**Comment by coldacid** [comment]
I've implemented itunes:block at the item level now. I need to trial out the episode refactoring that this work is based on before I can release 3.3.

For now, I'm going to skip on itunes:title since it would just have the same value as the regular item title tag.
