### ISSUE TITLE
Two bugs?

### ISSUE THREAD

**Issue by Marco-Lugo** [PodcastGenerator/PodcastGenerator#248]
System Information:
Podcast Generator Version: 3.0.1
PHP Version: 7.3.5

After a fresh install in the main page of Podcast Generator I have this warning:
Warning
: sizeof(): Parameter must be an array or an object that implements Countable in
/home/mhd-01/www.tearsinrain.it/htdocs/podcast/themes/default/listepisodes.php
on line
3

I don't know if it's a consequence of this warning message but I can't load themes.
In the themes page I can only read:
Change theme
You can upload themes to your themes/ folder
Installed themes

And no images of any theme are visible.

**Comment by emilengler** [comment]
> Installed themes

Where do you get the themes? AFAIK there is currently only one 3.0 theme available. Keep in mind that all old PG themes are incompatible.

**Comment by Marco-Lugo** [comment]
I can't see the "default" theme provided in the installation zip file.

**Comment by emilengler** [comment]
It is located under `PodcastGenerator/themes/default`

**Comment by Marco-Lugo** [comment]
Yes but you can see it in the "Change theme" page?
Me not.

**Comment by emilengler** [comment]
I still don't get what you mean.
Can you show me some screenshots?

**Comment by workaround** [comment]
Hi Marco,

to show the default theme in your 3.0.1 configuration you need to change the version for which theme is declared compatible.
To do that you must add 3.0.1 in file theme.json:
From: `"pg_versions": ["3.0"],`
To: `"pg_versions": ["3.0", "3.0.1"],`

In order to hide warning in file listepisodes.php you can simply add this check on top:
`if (!isset($episode_chunk)) { $episode_chunk = []; }`

Greetings,
Francesco

**Comment by Marco-Lugo** [comment]
Thanks workaround now work well. :)
