### ISSUE TITLE
PHP Problem

### ISSUE THREAD

**Issue by flomeixneryt** [PodcastGenerator/PodcastGenerator#278]
Hello, I have the following problem:

I have installed your software correctly on my server.

However, I get the following two messages on the main page

notice: Undefined index: explicit_podcast in /var/www/web92/htdocs/WEBVERZEICHNISSE/podcast/core/feed_generator.php on line 44

Notice: Undefined offset: 0 in /var/www/web92/htdocs/WEBVERZEICHNISSE/podcast/index.php on line 42

What can that be?

But otherwise I find a great software from you.

Sincerely yours
Florian Meixner

**Comment by emilengler** [comment]
Which webserver do you use?
This is an error of your webserver configuration. You need to disable displaying warnings and notices from PHP

**Comment by flomeixneryt** [comment]
Hello again

I think this should be an Apache server. But can not say exactly because it is only a web hosting offer and not a root server. therefore I do not know how I can turn off the messages. But I'll see if and where I can do it.

Thank you for your quick response.

**Comment by emilengler** [comment]
I think you should contact your server admin in that case maybe ask the support

**Comment by ryangurn** [comment]
Was there a specific action that you were performing to get that error? @flomeixneryt

**Comment by flomeixneryt** [comment]
@ryangurn No, I installed the software correctly and the error message came immediately after the installation

**Comment by flomeixneryt** [comment]
@emilengler I do not quite understand what you mean but I only rented the webspace but have no complete access to the server.

I apologize in advance because I'm still a newcomer. :smile:

**Comment by flomeixneryt** [comment]
I posted my page for you here so you can take a look:

[](https://livechat.flomeixner.de)

**Comment by emilengler** [comment]
> @emilengler I do not quite understand what you mean but I only rented the webspace but have no complete access to the server.
> 
> 
> 
> I apologize in advance because I'm still a newcomer. :smile: 

It's ok, everyone was a newcomer at some point ;)

In the case that you don't have access to the server I would suggest you to write a support ticket to your webspace hoster where you request that they should turn PHP warnings and errors off so they are not being shown on the page. Just curious, which hoster do you use? Maybe I can find some resources in their knowledge base if they have one

**Comment by ryangurn** [comment]
> @emilengler I do not quite understand what you mean but I only rented the webspace but have no complete access to the server.
> 
> I apologize in advance because I'm still a newcomer. 😄

I feel like a new programmer every day with all this new stuff now-a-days. It looks like you might be using internetwerk? @flomeixneryt

**Comment by ryangurn** [comment]
@flomeixneryt has there been any change to this?

**Comment by ryangurn** [comment]
@flomeixneryt was the webhost able to provide any help? If not, I have found [this stackoverflow](https://stackoverflow.com/questions/1053424/how-do-i-get-php-errors-to-display) which provide information about various ways to change the php error handling, both on a global level as well as just for this application. Please let me know if you have questions but I think that the answer discussing the .htaccess solution might work. I have included a snippet of that answer down below.


> (if you don't have access to php.ini, then putting this line in .htaccess might work too):
> php_flag display_errors 0

I have changed the 1 in the stackoverflow to a 0 so that you do not see those useless errors.

**Comment by garyee** [comment]
I do not know for you guys, but shuting of the error reporting instead of fixing the error ...  I don't know ;)

What version did you install?>
If it is not the latest version maybe try installing the latest version.

My take on this fro the first error would be:
The error means that you do not have the variable `explicit_podcast` set in your config
If you open the file `config.php` with an editor (wordpad or notepad++), look for:
`$explicit_podcast = ...` 
If you do not find it just add:
`$explicit_podcast = "no";` on a new line at before the line with  `// END OF CONFIG`

The other errors could maybe go away if you upload at least one episode. (as I do not know what version you are on)

**Comment by flattery103** [comment]
These are not errors. They are only notices and notices should never be displayed on a production server, but still good to clean up as garyee suggested.
