### ISSUE TITLE
Link to podcast file

### ISSUE THREAD

**Issue by tyler71** [PodcastGenerator/PodcastGenerator#308]
**Description**
Is it possible to just link to a podcast file instead of uploading it?
I would like to host them on a CDN

**Legal aspect**

* [x] I am the inventor of this idea or the idea is public domain
* [x] I release this idea into the public domain

**Comment by emilengler** [comment]
>  Is it possible to just link to a podcast file instead of uploading it?

Yes, since 3.1 we have such a feature.
However you first need to upload the episode. If you want to use the feature, do the following steps:
1. Upload the full episode normally
2. Go to the associated XML file in the media directory
3. Edit the linkPG value to a link to your CDN
4. Save the file
5. Delete the media file (mp3 or whatever) from your server
6. Click manually regenerate RSS feed
7. Have fun
