### ISSUE TITLE
Support webMaster and managingEditor tags

### ISSUE THREAD

**Issue by Saladoc** [PodcastGenerator/PodcastGenerator#311]
**Description**
The [RSS Specification](https://www.rssboard.org/rss-specification#optionalChannelElements) allows for two contacts to be specified, one for the person responsible for the content, one for the technical infrastructure. These contacts are not configurable and therefore not included in generated rss feeds.

**Motivation**
Many podcasts are collaborations and so responsibilities might be split between different people. Providing a way for efficiently contacting the reponsible person for different types of problems can only be beneficial, especially since the tags are optional and might be left out if their use is not desired.

**Legal aspect**

* [x] I am the inventor of this idea or the idea is public domain
* [x] I release this idea into the public domain

**Comment by ryangurn** [comment]
@Saladoc This is is super useful, I think that at this point @emilengler has added it to the version 3.2 milestone so that we keep it in mind for the newer version. I have personally worked on a few podcasts where there are multiple team members, so the rationale behind this is a very solid one. 

Thanks again for submitting this request.

**Comment by emilengler** [comment]
This feature is now in master. It will be shipped on 31th of December this year
