### ISSUE TITLE
Make Artwork filename adjustable

### ISSUE THREAD

**Issue by BPX400** [PodcastGenerator/PodcastGenerator#338]
Hi everyone,

By now the artwork filename of the podcast is hardcoded in the upload and rss-feed generation scripts to itunes_image.jpg. The value should be adjustable or selectable, e.g. by setting a global variable in the podcast configuration xml-file.

I noticed this as we wanted to update the artwork of our podcast and the change was not seen by several plattforms even when waiting a long time. When updating the artwork of a podcast, popular plattforms like iTunes or Spotify have issues noticing the change as the image url in the feed stays the same. See these FAQs for example: https://itunespartner.apple.com/podcasts/articles/artwork-3066
https://support.spotifyforpodcasters.com/hc/en-us/articles/360049349232-Changing-your-title-description-artwork-or-audio
By enabling the custom selection of the filename of the artwork, several problems can be resolved:
1. Ensuring the artwork is updated on all plattforms consistantly
2. multiple artworks can be uploaded, which then enables the possibility for "per episode artwork".
3. Seasons of podcasts can have their own artwork

Best regards,
Bastian

**Legal aspect**
* [x] I am the inventor of this idea or the idea is public domain
* [x] I release this idea into the public domain

**Comment by emilengler** [comment]
Sounds like a good idea

**Comment by coldacid** [comment]
For 3.2, we have renaming of the show cover art, based on the name of the uploaded file (it is not otherwise customizable, but itunes_image.jpg is no longer a fixed filename). Per-episode cover art is already supported, as long as it's embedded in the MP3 first, although there's an untested PR that adds support for uploading cover art image explicitly. Currently, there's no support for per-season artwork, and I don't anticipate anything happening on that front unless it gets adoption by Podcast Index and various podcast apps first.
