### ISSUE TITLE
Solution FAQ change website link not working

### ISSUE THREAD

**Issue by messagedj** [PodcastGenerator/PodcastGenerator#342]
**System Information**
Podcast Generator Version: 3.1

i want to change the website link in my feed. My problem is described at 
[https://podcastgenerator.net/documentation/FAQ-change-Website-Link ](https://podcastgenerator.net/documentation/FAQ-change-Website-Link )
but $feed_iTunes_LINKS_Website = ""; is not in the 3.1 config file. 

where can i change it?

**Comment by samisaacscreative** [comment]
You can edit the link for each show by adding a similar named VAR to the config.php file - giving it a value. 
I used this one: `$myWebsitePod = "https://mypod.com";` and added it to the bottom of my config.php file before the // END OF CONFIG comment.

You can then update the <link></link> element of your feed_generator.php file, located in the core folder, to point to our new var instead of the system generated one. Edit the original line in feed_generator.php on line 141:
`$item .= $indent . '<link>' . $config['url'] . '?' . $link . '=' . $files[$i]['filename'] . '</link>' . $linebreak;`
To:
`$item .= $indent . '<link>' . $config['userWebsitePod'] . '</link>' . $linebreak;`

Works fine my end! You may need to test and backup before going with it.

**Comment by emilengler** [comment]
I will close this for now. Let me know if the issue persists
