### ISSUE TITLE
HTTPS Setting

### ISSUE THREAD

**Issue by AlexEneas** [PodcastGenerator/PodcastGenerator#382]
Hello,
I'd like the links to the files on my server to show as HTTPS in the reed rather than HTTP. 
What setting do i need to change so I can get the generator to be able to do this please?

THanks

**Comment by coldacid** [comment]
@AlexEneas you need to update your config.php manually for this, since there's no option in the admin pages to do this. In that file, look for the line that starts like `$url =` and change the value next to it to say 'https' instead of 'http'. Then after regenerating your feed in the admin pages, it should point to HTTPS instead.

**Comment by samisaacscreative** [comment]
@AlexEneas, make sure you also have a .htaccess file that redirects the http requests to https. Here is an example one that works for me, no need to make any adjustments: 
`RewriteEngine ON

# Rewrite HTTP to HTTPS
RewriteCond %{ENV:HTTPS} !=on
RewriteRule ^.*$ https://%{SERVER_NAME}%{REQUEST_URI} [R,L]`

Save that as a .htaccess in your route directory.

**Comment by Go-rom** [comment]
@AlexEneas would you please provide a feedback on your issue et tell us if it's fixed or not ?
If it is, please close this ticket
