### ISSUE TITLE
Can't create new categories or upload album photo.

### ISSUE THREAD

**Issue by kyabocru** [PodcastGenerator/PodcastGenerator#386]
I have Podcast Generator on another website and it works fine. I have not updated it to this latest version I am now using at www.ipjb.org.br/podcast.

The php version is the latest one and I everything should be fine, but I can't get to creat new categories or upload album covers.

I have writen the ftp to 775 as it says in the configuration, but it also did not work.

I am able to upload files through the browser, but really can't create categories or upload the album art. Not even through the FTP.

I get error  HTTP ERROR 500

**System Information**
Podcast Generator Version: 3.1
Webserver: www.ipjb.org.br/podcast
PHP Version: 7.4

**Comment by kyabocru** [comment]
I am able to upload files through the browser, but really can't create categories or upload the album art. Not even through the FTP.

**Comment by Go-rom** [comment]
You didn't use the secured config tool in order to post your config.php without the sensitive informations.
It's clearly asked in the bug report template when you open a new ticket

**Comment by emilengler** [comment]
Can you at least post an error log?

**Comment by NedNet29** [comment]
Hi all, 
I recently installed Podcast Generator 3.1.1, did change dirs to 775 and files to 664, but I can't create categories : I too have a http 500 error after clicking "add" button, with a blank page displayed.
Attached is my config.php in which I anonymized $first_installation, $installationKey, $podcastPassword, $author_email and $users_json : 
[podcast_config_anonymized.php.txt](https://github.com/PodcastGenerator/PodcastGenerator/files/6308643/podcast_config_anonymized.php.txt)

Since i'ts hosted on a mutualized server (running PHP 7.3), I'm not sure I can access it's log files, but if there is anything I can provide helping solve this problem, just let me know.
TIA

**Comment by coldacid** [comment]
Sounds like an encoding error with PHP, then.

**Comment by emilengler** [comment]
@NedNet29 I cannot also reproduce on current git master meaning the problem is already fixed. I will ship PG 3.2 the next days try again and we will see then how we continue. For now I'll close that issue but I won't hesitate opening it again assuming the problem still persists for you

**Comment by NedNet29** [comment]
Ok thanks. I'll let you know as soon as I Upgraded to 3.2
