### ISSUE TITLE
simple download statistic

### ISSUE THREAD

**Issue by wandogau** [PodcastGenerator/PodcastGenerator#427]
**Description**
A simple statistic how often an episode has been accessed (downloaded or played). Just to have an overview if the number of listeners is growing. If one plays only a few seconds of an episode - does'nt matter in my opinion.
**Motivation**
We have some internet-statistics given by our provider but they are hard to find and I always forget where to find them. So it would be very great to have a simple statistic in the admin-panel.
**Legal aspect**

* [x] I am the inventor of this idea or the idea is public domain
* [x] I release this idea into the public domain

**Comment by coldacid** [comment]
As soon as a podcast aggregator service enters the picture, any access statistics you might get are skewed. All the big services and probably most of the smaller ones too will cache your episode on their own servers and maybe if you're lucky you can get access to their stats for your show. This is something that's been discussed before on Adam Curry and Dave Jones' *Podcasting 2.0* show for Podcast Index.

That said, it would certainly be possible to add a PHP script to Podcast Generator that increments a counter and then issues a redirect to the actual episode MP3. However anyone or anything that then accesses the MP3 directly after getting its URL from the redirect result from the script will also skew your results. Your best bet is to bookmark your provider's stats page since those are probably driven directly by the request log for the web server and give you the closest thing to the "ground truth" of how many requests are made to your show's website for each episode.

**Comment by wandogau** [comment]
Hello Chris,

Thanks a lot for your answer. What a pity, but we’ll take the stats of our provider.

Best

Moo

 

 

Von: Chris Charabaruk ***@***.***> 
Gesendet: Mittwoch, 9. Juni 2021 15:32
An: PodcastGenerator/PodcastGenerator ***@***.***>
Cc: wandogau ***@***.***>; Author ***@***.***>
Betreff: Re: [PodcastGenerator/PodcastGenerator] simple download statistic (#427)

 

As soon as a podcast aggregator service enters the picture, any access statistics you might get are skewed. All the big services and probably most of the smaller ones too will cache your episode on their own servers and maybe if you're lucky you can get access to their stats for your show. This is something that's been discussed before on Adam Curry and Dave Jones' Podcasting 2.0 show for Podcast Index.

That said, it would certainly be possible to add a PHP script to Podcast Generator that increments a counter and then issues a redirect to the actual episode MP3. However anyone or anything that then accesses the MP3 directly after getting its URL from the redirect result from the script will also skew your results. Your best bet is to bookmark your provider's stats page since those are probably driven directly by the request log for the web server and give you the closest thing to the "ground truth" of how many requests are made to your show's website for each episode.

**Comment by coldacid** [comment]
If it helps, there's at least one podcast service that provides a count of subscribers in its user-agent line. But yeah, podcast stats are a crapshoot thanks to all the different ways your episodes could be played or cached for multiple users. The good news is that the number of downloads you see will be the *minimum* number of overall downloads for an episode! But you'll never be able to get an accurate number of *plays* short of locking users into your own application, which would essentially remove your show from the podcasting ecosystem.

**Comment by srichakraway** [comment]
Hello, We are a spiritual center from India. We installed and tested your script on www.elokha.net/srichakraway. Its working well. But there is no function on admin screen to know how many listeners are hearing currently or even log/country. Bulk uploads will also be great as we have over 400 episodes to upload. Please also add a direct feedback/contact button on admin screen. Regards, Raj

**Comment by coldacid** [comment]
@srichakraway Live-listener stats would not be possible. As for any other stats, see above.
