### ISSUE TITLE
Prevent unauthorized listeners 

### ISSUE THREAD

**Issue by mishav78** [PodcastGenerator/PodcastGenerator#444]
Does the software prevent a person from listening to a certain podcast even if he knows the url if not properly authorized to listen?  For example not a paid subscriber.

**Comment by coldacid** [comment]
No, that's something that would need to be configured on the web server itself. Podcast Generator itself is unable to offer that functionality.

**Comment by mishav78** [comment]
what server would I use?

**Comment by coldacid** [comment]
It should be doable with any web server. You need to look into how to HTTP basic authentication for the website, depending on what server you use, and then configure the authentication appropriately for PG's media/ directory. If you are using shared hosting, it's very likely that your host provides Apache, but it is possible that they provide nginx instead. I suggest that you talk to your web host to find out what they provide and how you can configure it.

**Comment by mishav78** [comment]
can you do signed urls with apache or any other server that you know of?

**Comment by coldacid** [comment]
Signed?

**Comment by mishav78** [comment]
yes there is a certain way to prevent unauthorized listeners

**Comment by coldacid** [comment]
Okay, that's not what "signed" means, hence my confusion.

Every web server out there that isn't a toy has support for HTTP [basic authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) and the only trick is how to configure it. Apache, IIS, nginx, etc. all have their own systems for configuration. The onus is on you to figure out which server you're using and how to configure it. In the case of Apache, this will involve an .htaccess file and an .htpasswd file. For IIS, real user accounts are required on the server or the domain to which the server is attached. I don't even know how how nginx is configured for this, but I know that it can be.

What you want to do is use basic authentication to protect the contents of the PG media/ directory so that authorized listeners provide a username and password when downloading episodes of your podcast. You don't have to protect the rest of the site, although you can do so if you want. Whether you give everyone the same username and password, or give each subscriber their own, that's up to you to decide. Either case you'll need to keep the configuration up to date -- adding or removing entries from .htpasswd, or creating and disabling/deleting Windows (or Active Directory) accounts, etc.

On the client side, subscribers need to use a podcast player that supports basic authentication so that they can provide the username and password you give them in order to download and play episodes. Alternatively, they can download episodes via their web browser, using the same credentials, and play the episodes offline.

**Comment by mishav78** [comment]
Thanks, I'll check it out.
