### ISSUE TITLE
errors on Step 2 page of install

### ISSUE THREAD

**Issue by JustinWebDev** [PodcastGenerator/PodcastGenerator#453]
**System Information**
Podcast Generator Version:  3.1.2
Webserver:  PHP.exe
PHP Version: 7.4

**Podcast Generator Config**

```
(can't find any config file)
```  

**Expected behavior**
get two session_start errors
typo - "direcotires"

**Actual behavior**
Warning: session_start(): open(/tmp\sess_thkqobbdclcdcisrkapeoikke8, O_RDWR) failed: No such file or directory (2) in D:\WebDev\BBC\RSS\test\PodcastGenerator-3.1.2\PodcastGenerator\setup\step2.php on line 12

Warning: session_start(): Failed to read session data: files (path: /tmp) in D:\WebDev\BBC\RSS\test\PodcastGenerator-3.1.2\PodcastGenerator\setup\step2.php on line 12
Podcast Generator - Step 2

We are now checking if our data direcotires are writable so you can actual store the data.

**How to reproduce**
launch index.php from VSC with  PHP Server extension

**Comment by coldacid** [comment]
@JustinWebDev the config file is `PodcastGenerator/config.php` in your repo. Also, VS Code should be able to launch PG using the server built into the PHP executable itself so long as you also have XDebug installed and configured -- `.vscode/launch.json` contains the configuration for that. If you try with that instead of the PHP Server extension, you should be okay. Note that you need to run with the `PodcastGenerator/` directory inside the repo as the site root, not the repo root directory; from my understanding that means the `phpserver.relativePath` setting in VS Code would need to be `PodcastGenerator/` for your project.
