### ISSUE TITLE
PG 2.7 does not work on PHP 8+

### ISSUE THREAD

**Issue by TRNHOCKEY** [PodcastGenerator/PodcastGenerator#482]
**System Information**
Podcast Generator Version: 
Webserver: 
PHP Version:

**Podcast Generator Config**

**Actual behavior**
 

**How to reproduce**

**Comment by coldacid** [comment]
Please provide actual details about your Podcast Generator setup or we won't be able to help you. At the very minimum, you need to include the version of Podcast Generator that you're using, your version of PHP, and the scrubbed configuration for your Podcast Generator site, as well as what you did that caused the error and any messages returned by Podcast Generator.

**Comment by TRNHOCKEY** [comment]
PodcastGenerator-2.7 is what I'm using. Scrubbed version, not sure what that means. I tried setting back my php version (which was just upgraded this week to 8.0) to 7.4 but there is no place to do that. When I go to FTP [FTP Feature (Auto Indexing)](http://www.beyondthebeltway.com/podcastgen-2.7/PodcastGenerator-2.7/?p=admin&do=ftpfeature) I just get a blank page now after the php upgrade this week. Support at Bluehost is telling me to get my web people to update my scripts, etc. I'm old, what do I do?

**Comment by coldacid** [comment]
Well, you're running a very old version of Podcast Generator. First thing is that you'll need to upgrade to 3.0, since there's no support for a direct 2.7 to 3.1 upgrade. Then once you have 3.0 installed you'll need to upgrade again to 3.1.4.1 (the latest patch version of 3.1).

Podcast Generator 2.7 was developed and released long before I became involved with the project, so there's not much I can do to help you with it in particular, unfortunately. But 3.1 runs for sure with PHP 7.4 and 8.0.

**Comment by esposmusings** [comment]
@TRNHOCKEY, I use Bluehost as well, and I believe that when they upgraded PHP it broke the Podcast Generator 2.7 FTP Feature (Auto Indexing). Upgrade to 3.0.1. Then using Bluehost's Softaculous (My Installs) to upgrade to the latest version. I had to do this yesterday.

Also, change your image directory on line 19 of config.php. The default was the same as media, which created a confusing situation for me until I changed it.
