### ISSUE TITLE
RSS link not even recognized as RSS feed?????

### ISSUE THREAD

**Issue by 5280designco** [PodcastGenerator/PodcastGenerator#517]
Is there a reason why the RSS link isn't even recognized as a legit feed??? This is probably the most important issue possible??

![image](https://user-images.githubusercontent.com/73325867/161368820-e6b16790-f790-4db4-aca6-0866b2ee24f4.png)

**Comment by coldacid** [comment]
I don't know what app you screenshotted there, but I your feed URL through three different validators and they all check out. It seems the problem is with whatever app you have there.

- https://podba.se/validate/?url=https%3A%2F%2Fcorealty.co%2Ffeed.xml
- http://castfeedvalidator.net/?url=https://corealty.co/feed.xml
- https://www.castfeedvalidator.com/?url=https://corealty.co/feed.xml

**Comment by 5280designco** [comment]
Yeah, I tested others and it was fine too, which blows my mind because this screenshot is from Anchor.fm, the largest one. I opened a ticket with them
