### ISSUE TITLE
I must be missing something. Where is the SEARCH??? I can't imagine there would be no search option......................

### ISSUE THREAD

**Issue by 5280designco** [PodcastGenerator/PodcastGenerator#518]
**System Information**
Podcast Generator Version: 
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**

**Actual behavior**
 

**How to reproduce**

**Comment by coldacid** [comment]
Search is right underneath the podcast description and CTA buttons on every public page.

![image](https://user-images.githubusercontent.com/130681/161456726-f4702e97-08ea-42f7-836a-fa2718e026e1.png)

**Comment by 5280designco** [comment]
It's not showing on mine - https://corealty.co/podcast/

**Comment by 5280designco** [comment]
Also, does the pagination not supposed to be responsive?

**Comment by coldacid** [comment]
What version of Podcast Generator are you using? Search is not present in the theme in 3.0 and 3.1, as it was added after 3.1 was released. For the page bar, that's #510 which will be tackled for 3.3, but will probably be backported to 3.2 if the changes to fix it are minor.

**Comment by 5280designco** [comment]
3.1.4. Any reason why the latest versions are not updated on Softaculous? How can I update?

**Comment by coldacid** [comment]
I don't use or know anything about Softaculous, but right now 3.2 is only in beta (although at this point that is only because we are missing the completion of one translation that we did have in 3.1). It may be that Softaculous doesn't provide beta or release candidate versions of website applications.

If you are comfortable with a manual update process, you should be able to unzip https://github.com/PodcastGenerator/PodcastGenerator/releases/download/v3.2.0-beta.3/PodcastGenerator-v3.2.0-beta.3.zip and copy the contents of the PodcastGenerator/ directory from wherever you unzipped PodcastGenerator-v3.2.0-beta.3.zip over top of your existing Podcast Generator installation. (NB for anyone else looking at this issue: upgrading to 3.2 is only supported when running 3.1.x) After that, the next time you visit the site it will automatically update everything.

Make sure to back up your site first, just in case something goes wrong. If you have customized the default theme in any way, then it's even more important to back up, so you can reapply any customizations that haven't been superseded by 3.2's new features.

**Comment by 5280designco** [comment]
Cool, thx, updated

**Comment by 5280designco** [comment]
I was adding the below categories and as soon as I added the one in bold, it went to an error page, and I went back to categories page and they're ALL gone. When I try to add any, back to error page............Login is admin/pass

Ejemplos Buenos y malos
Estudio Carta de Santiago
Estudio Libro de Esdras
Estudio Libro de Hageo
Estudio Breve de Zacarías
**Filemón: El Perdón Bíblico**

**Comment by coldacid** [comment]
You shouldn't put your credentials out in public like that.

The only thing I can think of is that the colon character caused an error with the categories file. I'll open a new issue for tracking that.
