### ISSUE TITLE
PodcastGenerator 3.2 - Long Descriptiona and Short Description are swapped in Apple Podcast

### ISSUE THREAD

**Issue by sseguin613** [PodcastGenerator/PodcastGenerator#522]
**System Information**
Podcast Generator Version: 3.2 RC

It seems to be displaying the Long Description in the Episode List view (where you see all the podcast episodes) of the podcast show on Apple Podcasts, but using the Short Description in the actual Episode Display (where you only see the one selected episode). So something seems to be flipped.

This is the opposite of what the expected behaviour should be.

**Comment by coldacid** [comment]
I have to actually look into this one before I make any changes since different apps all do different things about long and short descriptions. Unfortunately descriptions and show notes are a complete minefield, one that hopefully will be solved soon with some additions to the [podcast namespace](https://github.com/Podcastindex-org/podcast-namespace) for RSS.
