### ISSUE TITLE
RSS not updated when future-dated episode is published

### ISSUE THREAD

**Issue by coldacid** [PodcastGenerator/PodcastGenerator#680]
I recently upgraded from 3.2.x (which was working without a problem to 3.2.7, and am experiencing problems with feed.xml being generated. If I upload a file, it generates fine. If I date it with a future publication date, it gets published on the web page, but the feed.xml is not generated automatically. If I log in, and click, Manually Regenerate RSS feed, it does. This should be automated.

_Originally posted by @srice777 in https://github.com/PodcastGenerator/PodcastGenerator/issues/578#issuecomment-1163139890_

**Comment by coldacid** [comment]
@srice777 are future-dated episodes showing up on the website automatically, or only after their publication date/time? If the former, then there's two bugs I need to fix.

**Comment by srice777** [comment]
Ok, I just checked this, and found out that it is publishing on the web page, but it is not updating the RSS Feed. A secondary issue I noticed, was the time being used didn't seem to be right with php. So, apparently my PHP is not configured to use my time zone.

**Comment by coldacid** [comment]
@srice777 I mean, are the future dated episodes showing up immediately (not automatically) or not until the publication date/time has passed? Because this could speak to multiple issues I need to fix.

**Comment by srice777** [comment]
Ok, so I ran another check. And the episode does publish on the website correctly, however the RSS Feed does not update. So there is only one issue that needs to be resolved.

**Comment by coldacid** [comment]
That makes my life easier!

**Comment by coldacid** [comment]
@srice777 Actually, do you have cron set up for your podcast site? On the Podcast Generator Configuration admin page, there's a URL that you should call regularly (once an hour or so) which regenerates the RSS feed, picking up any episodes which have been published since the last time the feed was refreshed.

Since PHP sites aren't something constantly running, the only reasonable way to automatically regenerate the RSS feed for future-dated episodes is by regularly hitting the pg-cron URL available on that admin page. So there's no development I can really do for this.

If your web host doesn't provide you with the ability to schedule "cron" jobs, there are online services like https://cron-job.org or https://www.easycron.com/ which can be used to access your site's custom pg-cron URL.

**Comment by srice777** [comment]
@coldacid 

My web hosting company does have the crontab stuff available, and I do have a few others running, however I'm not 100% sure how to run this one correctly. 
I tried to set it up before, however I didn't see the php link in the config file. So I tried to setup a crontab with the admin/episodes_regenerate.php but ran into problems because you had to be authenticated. I tried a few methods of authentication with php, but never succeeded.  
After you steered me to the link in the PG Config page, I tried a few methods that didn't seem to work.
`https://mywebsite.com/pg-cron.php?key=code232` (I did change the link and code for security)

I tried these in cli on the server:
`wget https://mywebsite.com/pg-cron.php?key=code232` - This just downloads a file.

`php https://mywebsite.com/pg-cron.php?key=code232`
Error returned from php code:
`Could not open input file: https://.....`

`curl https://mywebsite.com/pg-cron.php?key=code232`
`GET https://mywebsite.com/pg-cron.php?key=code232`
Error code from curl and GET:
`<html><head><title>Error 406 - Not Acceptable</title><head><body><h1>Error 406 - Not Acceptable</h1><p>Generally a 406 error is caused because a request has been blocked by Mod Security. If you believe that your request has been blocked by mistake please contact the web site owner.</p></body></html>`

When I paste that url in in a browser, it seems to work (blank page with no errors). 
If it isn't apparent, I'm not a dev, just a semi savvy self taught web guy. I would appreciate some help how to correctly call or use the link supplied in the PG Configuration page in a crontab. Thank you for the help, it is greatly appreciated. 

srice777

**Comment by srice777** [comment]
I think I found an answer:
`wget -O - -t 1 http://mywebsite.com/pg-cron.php?key=code232` 
This appears to work. I will know for sure when I actually schedule another podcast, and it automagically updates the feed.xml. Once, I know it works, I will add the -q option as well.

**Comment by srice777** [comment]
That line above is working perfectly! So this isn't a bug, but rather a pebkac error.

https://www.computerhope.com/jargon/p/pebkac.htm

lol.

**Comment by coldacid** [comment]
Well, it's also a wild goose chase on my part. I should have realized that the web cron is needed for this and could have gotten you the right info a lot earlier. Good to hear that all's well now though!

**Comment by srice777** [comment]
I almost mentioned this earlier. I tried to manually set a crontab but had to be logged in to run it, so I tried several times to figure out how to pass the info, and couldn’t figure it out. 

Now that you mentioned that on the Configuration page, I’m not sure how I overlooked that!  Is that supposed to be run with php?  like this:

php https://mypodcastinstall.com/pg-cron.php?key=nottherealkey

I tried a few others too, wget, GET, curl, and I’m not sure how to run the crontab. I have ssh access, and cpanel access where I can schedule a crontab. I’m sure there is simple syntax, I just don’t know how to do it.

Thank you for the help on this!

Shane

**Comment by coldacid** [comment]
You should be using curl or wget to HTTP GET the pg-cron.php page with the instalation key, e.g.

```sh
$ curl 'https://mypodcastinstall.com/pg-cron.php?key=nottherealkey'
```

Your wget line in an earlier comment should also work.

As for crontab, it is not that easy a syntax and the fact that most systems are set up to use vi as the crontab editor doesn't help. However, there are free and cheap online services like EasyCron that you can use to avoid the complexity of editing a crontab file, or you can use something like https://crontab-generator.org/ to at least determine what you should put into your crontab file. (Using vi is left as an exercise to the reader; mainly because even I don't know how to use it.)
